export const FILL_TABLE = 'FILL_TABLE';
export const CLEAR_TABLE = 'CLEAR_TABLE';

export const ERR_404 = 'ERR_404';
export const ERR_404_GONE = 'ERR_404_GONE';

export const VALID_INPUT = 'VALID_INPUT';
export const NOT_VALID_INPUT = 'NOT_VALID_INPUT';

export const LOAD_START = 'LOAD_START';
export const LOAD_SUCCESS = 'LOAD_SUCCESS';
export const LOAD_FAILS = 'LOAD_FAILS';

export const PAGINATION_INIT = 'PAGINATION_INIT';
export const PAGINATION_UPDATE = 'PAGINATION_UPDATE';
export const PAGINATION_RESET = 'PAGINATION_RESET';

export const INIT_TARGET_REPO_NAME = 'INIT_TARGET_REPO_NAME';
export const CLEAR_TARGET_REPO_NAME = 'CLEAR_TARGET_REPO_NAME';
